// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'firebase_options.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// Platform  Firebase App Id
//web       1:880621036129:web:a4346376a3a3736a3bc020
//android   1:880621036129:android:a97382f11a5e63383bc020
//ios       1:880621036129:ios:ad93fb8ff9a5a7743bc020
//macos     1:880621036129:ios:ad93fb8ff9a5a7743bc020
//windows   1:880621036129:web:b5dcb9717cd45ccf3bc020

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSAVo_XYYTKGUFWi6OC9bODMl2Pgnawfs',
    appId: '1:880621036129:web:a4346376a3a3736a3bc020',
    messagingSenderId: '880621036129',
    projectId: 'genesapp-960d8',
    authDomain: 'genesapp-960d8.firebaseapp.com',
    storageBucket: 'genesapp-960d8.firebasestorage.app',
    measurementId: 'G-TBSC7B3M8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzY-o8Fk3oEeYe0TEO7j-KV0cR3yGQtKM',
    appId: '1:880621036129:android:a97382f11a5e63383bc020',
    messagingSenderId: '880621036129',
    projectId: 'genesapp-960d8',
    storageBucket: 'genesapp-960d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMoppNmfP8zJi6LT2UaowKtbKwNfLwrfI',
    appId: '1:880621036129:ios:ad93fb8ff9a5a7743bc020',
    messagingSenderId: '880621036129',
    projectId: 'genesapp-960d8',
    storageBucket: 'genesapp-960d8.firebasestorage.app',
    iosBundleId: 'com.example.genesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMoppNmfP8zJi6LT2UaowKtbKwNfLwrfI',
    appId: '1:880621036129:ios:ad93fb8ff9a5a7743bc020',
    messagingSenderId: '880621036129',
    projectId: 'genesapp-960d8',
    storageBucket: 'genesapp-960d8.firebasestorage.app',
    iosBundleId: 'com.example.genesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSAVo_XYYTKGUFWi6OC9bODMl2Pgnawfs',
    appId: '1:880621036129:web:b5dcb9717cd45ccf3bc020',
    messagingSenderId: '880621036129',
    projectId: 'genesapp-960d8',
    authDomain: 'genesapp-960d8.firebaseapp.com',
    storageBucket: 'genesapp-960d8.firebasestorage.app',
    measurementId: 'G-DGC6F79D76',
  );
}
